import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{'Twugo\'s Homepage'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1>
          {'Welcome to Twugo\'s Homepage!'}
        </h1>

        <p>
        </p>


      </main>
    </div>
  )
}

export default Home
